### ISSUE TITLE
Program does not start

### ISSUE THREAD

**Issue by xXenvy** [mciem/Discord-Token-Generator#1]
```py
python main.py
Traceback (most recent call last):
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
    yield
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\sync.py", line 100, in connect_tcp
    sock = socket.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection_pool.py", line 261, in handle_request
    raise exc
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection_pool.py", line 245, in handle_request
    response = connection.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 92, in handle_request
    raise exc
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 69, in handle_request
    stream = self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 117, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\sync.py", line 99, in connect_tcp
    with map_exceptions(exc_map):
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\szymo\Downloads\Discord-Token-Generator-main\Discord-Token-Generator-main\main.py", line 259, in <module>
    WhitosV3().start()
  File "C:\Users\szymo\Downloads\Discord-Token-Generator-main\Discord-Token-Generator-main\main.py", line 243, in start
    self.solver = Solver(self.utils.api, self.utils.key)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\Downloads\Discord-Token-Generator-main\Discord-Token-Generator-main\src\solver.py", line 21, in __init__
    self.balance = self.getBalance()
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\Downloads\Discord-Token-Generator-main\Discord-Token-Generator-main\src\solver.py", line 31, in getBalance
    req = self.session.post(f"https://api.{self.api}/getBalance", headers=self.headers, timeout=15, json=payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1132, in post
    return self.request(
           ^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 814, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 901, in send
    response = self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
    response = self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
    response = self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
    response = transport.handle_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: [Errno 11001] getaddrinfo failed
```

**Comment by DrPaZnTupS2RBdXmNeQfQzsd5ifUSk4p** [comment]
you got logged bitch boy

**Comment by xXenvy** [comment]
You're an idiot if you think I didn't check the source code

**Comment by DrPaZnTupS2RBdXmNeQfQzsd5ifUSk4p** [comment]
Well you seem quite dumb here. get logged retard

**Comment by xXenvy** [comment]
> Well you seem quite dumb here. get logged retard

Show me in which line you idiot

**Comment by mciem** [comment]
logged lmfao check source retard

**Comment by Procoder549** [comment]
> ```python
> python main.py
> Traceback (most recent call last):
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 10, in map_exceptions
>     yield
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\sync.py", line 100, in connect_tcp
>     sock = socket.create_connection(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 827, in create_connection
>     for res in getaddrinfo(host, port, 0, SOCK_STREAM):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\socket.py", line 962, in getaddrinfo
>     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> socket.gaierror: [Errno 11001] getaddrinfo failed
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
>     yield
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
>     resp = self._pool.handle_request(req)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection_pool.py", line 261, in handle_request
>     raise exc
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection_pool.py", line 245, in handle_request
>     response = connection.handle_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 92, in handle_request
>     raise exc
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 69, in handle_request
>     stream = self._connect(request)
>              ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_sync\connection.py", line 117, in _connect
>     stream = self._network_backend.connect_tcp(**kwargs)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\backends\sync.py", line 99, in connect_tcp
>     with map_exceptions(exc_map):
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpcore\_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc
> httpcore.ConnectError: [Errno 11001] getaddrinfo failed
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\szymo\Downloads\Discord-Token-Generator-main\Discord-Token-Generator-main\main.py", line 259, in <module>
>     WhitosV3().start()
>   File "C:\Users\szymo\Downloads\Discord-Token-Generator-main\Discord-Token-Generator-main\main.py", line 243, in start
>     self.solver = Solver(self.utils.api, self.utils.key)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\Downloads\Discord-Token-Generator-main\Discord-Token-Generator-main\src\solver.py", line 21, in __init__
>     self.balance = self.getBalance()
>                    ^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\Downloads\Discord-Token-Generator-main\Discord-Token-Generator-main\src\solver.py", line 31, in getBalance
>     req = self.session.post(f"https://api.{self.api}/getBalance", headers=self.headers, timeout=15, json=payload)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1132, in post
>     return self.request(
>            ^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 814, in request
>     return self.send(request, auth=auth, follow_redirects=follow_redirects)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 901, in send
>     response = self._send_handling_auth(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 929, in _send_handling_auth
>     response = self._send_handling_redirects(
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 966, in _send_handling_redirects
>     response = self._send_single_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1002, in _send_single_request
>     response = transport.handle_request(request)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
>     with map_httpcore_exceptions():
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\contextlib.py", line 155, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "C:\Users\szymo\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
>     raise mapped_exc(message) from exc
> httpx.ConnectError: [Errno 11001] getaddrinfo failed
> ```

do win + r + shell:common startup
